### ISSUE TITLE
Sorting of songs (right-hand column) in media library seems inconsistent.

### ISSUE THREAD

**Issue by josswright** [arybczak/ncmpcpp#231]
In the media library, I can't work out what the default sort order is for songs in the right-hand column when there isn't meaningful track information.

My main usage here is for podcasts, which are typically not given track numbers. My expectation was that the tracks would be listed in lexical order, but that doesn't seem to be the case. I set all my podcast downloads to be named <date>-<podcast_name>-<title>, in both filename and the title in their ID3 tags.

Here's a brief output of my current right-hand media library column from a random podcast:

```
2016-12-15 - MAG 43 Section
2017-02-16 - MAG 52 Exceptional Risk
2017-02-09 - MAG 51 High Pressure
2017-02-02 - MAG 50 Foundations
2017-01-26 - MAG 49 The Butcher’s Window
2017-01-19 - MAG 48 Lost in The Crowd
2017-01-12 - MAG 47 The New Door
```

I've just checked, and there's no date/year that I've added to the ID3 tags. What is the expected behaviour here? Is there any way to set these to sort by title?

**Comment by arybczak** [comment]
Should be fixed now (see referenced PR for more details).

**Comment by josswright** [comment]
I hate to say it, but it still doesn't seem to work. :(

For the podcast I'd referenced, I'm now getting appropriately ordered files. For another, I'm getting ones that seem correctly ordered by year, but the months and days are still random. Sample output from the right-hand column:

`2016-08-16 - Episode 212 - The Axis Mundi`
`2016-01-19 - Episode 201 - Sleepless in Seattle`
`2016-07-19 - Episode 210 - Welcome to the Machine`
`2016-06-21 - Episode 208 - Riverview`
`2016-04-24 - ALEX SLEEP NOTE #2`
`2016-05-24 - Episode 206 - All in the Family`
`2016-10-30 - THE BLACK TAPES HALLOWEEN 2016 BONUS`
`2017-10-10 - Episode 304 - Songs and Signs`
`2017-09-12 - Episode 302 - The Musica Mundana`
`2017-10-24 - Episode 305 - Worlds Collide`
`2017-09-26 - Episode 303 - A Family Gathering`
`2017-10-27 - Alex 2017 Halloween Announcement`
`2017-02-28 - ALEX ANNOUNCEMENT`
`2017-08-29 - Episode 301 - The Sins of the Father`

It feels like far too much effort going into this for a fairly unusual and seemingly minor annoyance, so I'm happy to live with it. I just wanted to register that it's still not quite sorted out! Thanks for all your help on this!
